### ISSUE TITLE
fuse-sdk@1.13.0 installation error or Ubuntu 16.04

### ISSUE THREAD

**Issue by ansarizafar** [fuse-open/fuse-sdk#3]
I am trying to install fuse-sdk@1.13.0 on Ubuntu 16.04 with nodejs 12.9.0. I have already installed Mono from this link https://www.mono-project.com/download but I am still getting error ERROR: Mono (>= 5.4.1.7) was not found.

![image](https://user-images.githubusercontent.com/5788284/68596971-f42ad800-04bd-11ea-9ad6-6087ca52f2b9.png)

**Comment by mortend** [comment]
Oh. :/

Can you please provide the output of these commands?

```
which mono
mono --version
mono --version | head -n1 | egrep -o '[0-9].*-[0-9]' | awk '{print $1;}'
```

**Comment by ansarizafar** [comment]
Here is the output of these commands

![image](https://user-images.githubusercontent.com/5788284/68636881-dc377080-051e-11ea-9866-e19d4b734932.png)

**Comment by mortend** [comment]
Thank you!

**Comment by mortend** [comment]
I've published a new version of [`dotnet-run`](https://github.com/mortend/dotnet-run).

If you reinstall the problem should be fixed.

**Comment by mortend** [comment]
Closing the issue, please reopen again if the problem persists.
